import Head from "next/head";
import { Fragment, useState } from "react";

import { createTheme, ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import Box from "@mui/material/Box";

import AdminAppBar from "../components/admin/AdminAppBar";
import { MenuContextWrapper } from "../context/MenuContext";
import AdminDrawer from "../components/admin/AdminDrawer";

const mdTheme = createTheme();

export default function AdminLayout({ children }) {
  const [open, setOpen] = useState(true);
  const toggleDrawer = () => {
    setOpen(!open);
  };

  return (
    <MenuContextWrapper>
      <Fragment>
        <Head>
          <title>Pusher Edu</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="initial-scale=1, width=device-width" />
          <link rel="icon" href="/favicon.ico" />
          {/* Roboto font - from tuts on MUI */}
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
          />
          {/* Font icons - from tuts on MUI */}
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/icon?family=Material+Icons"
          />
        </Head>

        <main>
          <ThemeProvider theme={mdTheme}>
            <Box sx={{ display: "flex" }}>
              <CssBaseline />
              <AdminAppBar />
              <AdminDrawer />
              {children}
            </Box>
          </ThemeProvider>
        </main>
      </Fragment>
    </MenuContextWrapper>
  );
}
