import Head from 'next/head';
import * as React from 'react';
import { Fragment, useState, useEffect } from 'react';

import { createTheme, ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import Box from '@mui/material/Box';

import TheAppBar from '../components/TheAppBar';
import { MenuContextWrapper } from '../context/MenuContext';
import TheDrawer from '../components/user/TheDrawer';

import { getUser } from '../store';
const mdTheme = createTheme();

export default function DefaultLayout({ children, title = 'Pusher Edu' }) {
  const [open, setOpen] = useState(true);
  const toggleDrawer = () => {
    setOpen(!open);
  };

  const [dataUser, setDataUser] = useState({});
  const { fetchDataUser } = getUser();

  const getDataUser = async () => {
    const data = await fetchDataUser();
    setDataUser(data);
  };

  useEffect(() => {
    const tokens = localStorage.getItem('tokens');
    console.log('tokens', tokens);
    if (tokens) getDataUser();
  }, []);

  return (
    <MenuContextWrapper>
      <Fragment>
        <Head>
          <title>{title}</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="initial-scale=1, width=device-width" />
          <link rel="icon" href="/img/logo.png" />
          {/* Roboto font - from tuts on MUI */}
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
          />
          {/* Font icons - from tuts on MUI */}
          <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
        </Head>

        <main>
          <ThemeProvider theme={mdTheme}>
            <Box sx={{ display: 'flex' }}>
              <CssBaseline />
              <TheAppBar dataUser={dataUser} />
              <TheDrawer />
              {children}
            </Box>
          </ThemeProvider>
        </main>
      </Fragment>
    </MenuContextWrapper>
  );
}
